# Generated by Django 2.1.2 on 2019-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacioninterna',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'comunicación interna', 'verbose_name_plural': 'comunicacion_interna internas'},
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
