# Generated by Django 2.1.2 on 2019-08-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0012_auto_20190824_2256'),
        ('notificaciones', '0002_auto_20190823_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacioninterna',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'comunicación interna', 'verbose_name_plural': 'comunicacion_interna internas'},
        ),
        migrations.RemoveField(
            model_name='comunicacioninterna',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='reserva',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='agendas.Agenda', verbose_name='reserva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='mensaje leido'),
        ),
    ]
