# Generated by Django 2.1.2 on 2019-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190518_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(default=3184223624, max_length=40, verbose_name='celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(max_length=40, null=True, verbose_name='numero de documento'),
        ),
    ]
