# Generated by Django 2.1.2 on 2019-06-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190622_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='codigo de verificación'),
        ),
    ]
