# Generated by Django 2.1.2 on 2019-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_codigo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_solicitud_codigo_verificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima fecha en que solicito el codigo'),
        ),
    ]
