# Generated by Django 2.1.2 on 2019-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_user_fecha_solicitud_codigo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfil', verbose_name='foto de perfil'),
        ),
    ]
