# Generated by Django 2.1.2 on 2019-09-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_user_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('es_administrativo', 'Perfil administrativo'), ('es_docente', 'Perfil docente'), ('es_servicios_generales', 'Perfil servicios generales')), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
