# Generated by Django 2.1.2 on 2019-05-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaRecursoFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='recursos/fisicos', verbose_name='imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaleriaRecursoTecnologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='recursos/tecnologicos', verbose_name='imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='numero')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='contenido')),
                ('caracteristicas', models.TextField(blank=True, null=True, verbose_name='caracteristicas')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='TipoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de aula',
                'verbose_name_plural': 'tipos de aula',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de equipo',
                'verbose_name_plural': 'tipos de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecursoFisico',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recursos.Recurso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='nombre')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='capacidad')),
                ('ubicacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='ubicación')),
                ('tipo_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.TipoAula', verbose_name='tipo de aula')),
            ],
            options={
                'verbose_name': 'recurso fisico',
                'verbose_name_plural': 'recursos fisicos',
                'ordering': ['nombre'],
            },
            bases=('recursos.recurso', models.Model),
        ),
        migrations.CreateModel(
            name='RecursoTecnologico',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recursos.Recurso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='nombre')),
                ('marca', models.CharField(blank=True, max_length=40, null=True, verbose_name='marca')),
                ('referencia', models.CharField(blank=True, max_length=40, null=True, verbose_name='referencia')),
                ('color', models.CharField(blank=True, max_length=40, null=True, verbose_name='color')),
                ('tipo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.TipoEquipo', verbose_name='tipo de equipo')),
            ],
            options={
                'verbose_name': 'recurso tecnologico',
                'verbose_name_plural': 'recursos tecnologicos',
                'ordering': ['nombre'],
            },
            bases=('recursos.recurso', models.Model),
        ),
        migrations.AddField(
            model_name='galeriarecursotecnologico',
            name='recurso_tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.RecursoTecnologico', verbose_name='recurso tecnologico'),
        ),
        migrations.AddField(
            model_name='galeriarecursofisico',
            name='recurso_fisico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.RecursoFisico', verbose_name='recurso fisico'),
        ),
    ]
