# Generated by Django 2.1.2 on 2019-04-27 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='numero')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='contenido')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='TipoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de aula',
                'verbose_name_plural': 'tipos de aula',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de equipo',
                'verbose_name_plural': 'tipos de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecursoFisico',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recursos.Recurso')),
                ('nombre', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='nombre')),
                ('tipo_aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.TipoAula', verbose_name='tipo de aula')),
            ],
            options={
                'verbose_name': 'recurso fisico',
                'verbose_name_plural': 'recursos fisicos',
                'ordering': ['nombre'],
            },
            bases=('recursos.recurso',),
        ),
        migrations.CreateModel(
            name='RecursoTecnologico',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recursos.Recurso')),
                ('nombre', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='nombre')),
                ('tipo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.TipoEquipo', verbose_name='tipo de equipo')),
            ],
            options={
                'verbose_name': 'recurso fisico',
                'verbose_name_plural': 'recursos fisicos',
                'ordering': ['nombre'],
            },
            bases=('recursos.recurso',),
        ),
    ]
