# Generated by Django 2.1.2 on 2019-05-11 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursofisico',
            name='nombre',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=40, unique=True, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recursotecnologico',
            name='nombre',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=40, unique=True, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
