# Generated by Django 2.1.2 on 2019-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20190511_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursofisico',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='recursotecnologico',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='nombre'),
        ),
    ]
