# Generated by Django 2.1.2 on 2019-04-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20190426_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursotecnologico',
            options={'ordering': ['nombre'], 'verbose_name': 'recurso tecnologico', 'verbose_name_plural': 'recursos tecnologicos'},
        ),
        migrations.AddField(
            model_name='recurso',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='caracteristicas'),
        ),
        migrations.AddField(
            model_name='recursofisico',
            name='capacidad',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='capacidad'),
        ),
    ]
