# Generated by Django 2.1.2 on 2019-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20190427_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursofisico',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='capacidad'),
        ),
    ]
