# Generated by Django 2.1.2 on 2019-08-14 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20190625_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursofisico',
            options={'ordering': ['nombre'], 'verbose_name': 'recurso físico', 'verbose_name_plural': 'recursos fisicos'},
        ),
        migrations.AlterModelOptions(
            name='recursotecnologico',
            options={'ordering': ['nombre'], 'verbose_name': 'recurso tecnólogico', 'verbose_name_plural': 'recursos tecnologicos'},
        ),
        migrations.AlterField(
            model_name='galeriarecursofisico',
            name='recurso_fisico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_rf', to='recursos.RecursoFisico', verbose_name='recurso físico'),
        ),
        migrations.AlterField(
            model_name='galeriarecursotecnologico',
            name='recurso_tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_rt', to='recursos.RecursoTecnologico', verbose_name='recurso tecnólogico'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='características'),
        ),
    ]
