# Generated by Django 2.1.2 on 2019-04-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_recursofisico_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursotecnologico',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='recursotecnologico',
            name='marca',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='recursotecnologico',
            name='referecia',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='referencia'),
        ),
    ]
