# Generated by Django 2.1.2 on 2019-04-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_auto_20190427_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursotecnologico',
            old_name='refenrecia',
            new_name='referencia',
        ),
    ]
