# Generated by Django 2.1.2 on 2019-04-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0009_auto_20190427_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaRecursoFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen')),
                ('recurso_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.RecursoFisico', verbose_name='recurso fisico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaleriaRecursoTecnologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen')),
                ('recurso_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.RecursoTecnologico', verbose_name='recurso tecnologico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
