# Generated by Django 2.1.2 on 2019-05-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0010_galeriarecursofisico_galeriarecursotecnologico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeriarecursotecnologico',
            old_name='recurso_fisico',
            new_name='recurso_tecnologico',
        ),
        migrations.AlterField(
            model_name='galeriarecursofisico',
            name='imagen',
            field=models.ImageField(upload_to='recursos/fisicos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='galeriarecursotecnologico',
            name='imagen',
            field=models.ImageField(upload_to='recursos/tecnologicos', verbose_name='imagen'),
        ),
    ]
