# Generated by Django 2.1.2 on 2019-05-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrreraProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=40, null=True, verbose_name='numero de documento')),
                ('nombres', models.CharField(max_length=40, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=40, null=True, verbose_name='apellidos')),
                ('celular', models.CharField(max_length=40, verbose_name='celular')),
                ('correo_electronico', models.EmailField(max_length=40, null=True, verbose_name='correo electronico')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('edad', models.IntegerField(blank=True, default=0, null=True, verbose_name='edad')),
            ],
        ),
        migrations.CreateModel(
            name='TituloObtenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'titulo',
                'verbose_name_plural': 'titulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplicaciones.talento_humano.Persona')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('carrera_profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.talento_humano.CarrreraProfesional', verbose_name='carrera profesional')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.talento_humano.Perfil', verbose_name='perfil')),
                ('titulo_obtenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.talento_humano.TituloObtenido', verbose_name='titulo obtenido')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['nombres'],
            },
            bases=('talento_humano.persona', models.Model),
        ),
    ]
