# Generated by Django 2.1.2 on 2019-06-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0002_empleado_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['usuario'], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='numero_documento',
        ),
    ]
