# Generated by Django 2.1.2 on 2019-07-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'agenda', 'verbose_name_plural': 'agendas'},
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_devolucion',
            field=models.TimeField(default='14:00:00', verbose_name='Hora de Devolución'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_separacion',
            field=models.TimeField(default='16:00:00', verbose_name='Hora de Separación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_devolucion',
            field=models.DateField(verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
