# Generated by Django 2.1.2 on 2019-07-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_auto_20190715_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='fecha_devolucion',
        ),
    ]
