# Generated by Django 2.1.2 on 2019-08-19 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_auto_20190814_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 19, 0, 0), verbose_name='Fecha de Separación'),
        ),
    ]
