# Generated by Django 2.1.2 on 2019-08-20 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_auto_20190819_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 20, 0, 0), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='recurso_tecnologico',
            field=models.ManyToManyField(blank=True, related_name='agenda_recurso', to='recursos.RecursoTecnologico', verbose_name='recurso tecnólogico'),
        ),
    ]
