# Generated by Django 2.1.2 on 2019-08-23 04:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendas', '0006_auto_20190820_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Entregado'), ('R', 'Recibido')], default='P', max_length=1, verbose_name='estado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='observacion')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='encargado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 22, 0, 0), verbose_name='Fecha de Separación'),
        ),
        migrations.AddField(
            model_name='minuta',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_agenda', to='agendas.Agenda', verbose_name='reserva en la agenda'),
        ),
    ]
