# Generated by Django 2.1.2 on 2019-08-23 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_auto_20190822_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 4, 22, 32, 284851, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
    ]
