# Generated by Django 2.1.2 on 2019-08-23 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0008_auto_20190822_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 12, 48, 15, 268520, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_agenda', to='agendas.Agenda', verbose_name='reserva en la agenda'),
        ),
    ]
