# Generated by Django 2.1.2 on 2019-08-23 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0009_auto_20190823_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 12, 50, 20, 252006, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='encargado'),
        ),
    ]
