# Generated by Django 2.1.2 on 2019-08-23 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0010_auto_20190823_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 13, 22, 58, 5567, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
    ]
