# Generated by Django 2.1.2 on 2019-08-25 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0011_auto_20190823_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 25, 3, 52, 24, 61299, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
    ]
