# Generated by Django 2.1.2 on 2019-08-25 04:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0012_auto_20190824_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 25, 4, 1, 45, 985235, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_agenda', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
