# Generated by Django 2.1.2 on 2019-08-25 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0013_auto_20190824_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 25, 4, 4, 16, 291765, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
    ]
