# Generated by Django 2.1.2 on 2019-08-26 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0014_auto_20190824_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 9, 58, 49, 225932, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
    ]
