# Generated by Django 2.1.2 on 2019-08-26 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0015_auto_20190826_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 10, 43, 37, 788113, tzinfo=utc), verbose_name='Fecha de Separación'),
        ),
    ]
