# Generated by Django 2.1.2 on 2019-08-26 20:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendas', '0016_auto_20190826_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuta',
            name='encargado',
        ),
        migrations.AddField(
            model_name='minuta',
            name='servicios_generales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='servicios generales'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 20, 10, 48, 636118), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='estado',
            field=models.CharField(choices=[('E', 'Entregado'), ('R', 'Recibido')], max_length=1, verbose_name='estado'),
        ),
    ]
