# Generated by Django 2.1.2 on 2019-08-26 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0017_auto_20190826_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuta',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 22, 21, 31, 461353), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 22, 21, 31, 456351), verbose_name='Fecha de Separación'),
        ),
    ]
