# Generated by Django 2.1.2 on 2019-09-01 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0018_auto_20190826_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'permissions': (('ver_agenda_general', 'Ver agenda general'),), 'verbose_name': 'agenda', 'verbose_name_plural': 'agendas'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 17, 47, 27, 981038), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 17, 47, 27, 985034), verbose_name='Fecha de Separación'),
        ),
    ]
