# Generated by Django 2.1.2 on 2019-09-01 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0019_auto_20190901_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_separacion',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 20, 51, 16, 367953), verbose_name='Fecha de Separación'),
        ),
        migrations.AlterField(
            model_name='minuta',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 20, 51, 16, 372950), verbose_name='Fecha de Separación'),
        ),
    ]
